### ISSUE TITLE
Dynamic task mapping using Xcoms

### ISSUE THREAD

**Issue by vvsivaprasadreddy** [astronomer/dag-factory#155]
Is there a way to define Yaml dag to create dynamic task mapping just like use do using partial() and expand() functions? Can you give me an example?

Also, the Xcoms passed through Yaml are coming a string instead of python objects? Any solution?

**Comment by matveykortsev** [comment]
Created PR for that #162.
For passing Xcoms as a native Python object we need to add support of render_template_as_native_obj in dag params

**Comment by tatiana** [comment]
I believe there is support for dynamic task mapping since DAG factory [v0.18.0](https://github.com/astronomer/dag-factory/releases/tag/v0.18.0).

There is an example DAG and configuration file that works with task mapping:
https://github.com/astronomer/dag-factory/blob/main/dev/dags/example_task_group.py
https://github.com/astronomer/dag-factory/blob/main/dev/dags/example_task_group.yml

It uses the functions defined in:
https://github.com/astronomer/dag-factory/blob/main/dev/dags/expand_tasks.py

Please let us know if you face any issues - I'm closing this for now.
